OnChain part. Plutarch v2
ergolabs/cardano-dex-contracts pull request #56
Opened 2022-08-11 13:44 UTC by Bromel777

2022-08-12 10:01 UTC, yasha-black commented
Task linked: [CU-2vcg3fp onchain part](https://app.clickup.com/t/2vcg3fp)

2022-08-15 14:05 UTC, GusevTimofey requested changes

2022-08-17 09:04 UTC, oskin1 reviewed
Why V1 context is mixed with V2?
(Resolved)

2022-08-17 09:23 UTC, oskin1 approved these changes

2022-08-21 12:48 UTC, merged